language: python
python: ['3.6']
cache: pip
script: pytest
sudo: required
services: [docker]
install:
    - docker-compose build db
    - pip install -r requirements.txt
    - pip install common/
    - pip install pytest-timeout
