language: python
python: ['3.6']
script: pytest
sudo: required
services: [docker]
install:
    - pip install sync/requirements.txt

after_success:
    if [ ! -z "$TRAVIS_TAG" ]; then
       docker-compose build;
       docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
       docker-compose push;
    fi

