---
# This compose file is meant for use in deployment
version: '3.2'
services:

  web:
    image:    "drytoastman/scweb:${TAG:-latest}"
    volumes:  
        - "dbsocket:/var/run/postgresql"
    networks: { net1: }
    ports:    ["80:80"]

  db:
    image:    "drytoastman/scdb:${TAG:-latest}"
    volumes:  
        - "database:/var/lib/postgresql/data"
        - "dbsocket:/var/run/postgresql"
    networks: { net1: }
    ports:    ["54329:5432"]

networks:
  net1:
    ipam:
      driver: default
      config: [ subnet: "192.168.24.0/24" ]

volumes:
  database:
  dbsocket:

