---
# This compose file is meant for use in deployment
version: '3.2'
services:

  web:
    image:    "drytoastman/nwrscweb:${TAG:-latest}"
    networks: { net1: }
    ports:    ["80:80"]

  db:
    image:    "drytoastman/nwrscdb:${TAG:-latest}"
    volumes:  ["database:/var/lib/postgresql/data"]
    networks: { net1: }
    ports:    ["127.0.0.1:54329:5432"]

networks:
  net1:
    ipam:
      driver: default
      config: [ subnet: "192.168.24.0/24" ]

volumes:
  database:

