---
# This compose file is meant for development purposes
# It mounts the local user's directory and creates a link in the web container
# so that it uses the local copy of the web service
#
# We use a script to create a docker-compose file for deployment with specific
# images on docker hub and remove the extra developement features

version: '3.2'
services:

  web:
    build:   "web"
    command: "ash -c 'pip install -e /code && exec webserver.py'"
    environment:
        - DEBUG=1
        - LOG_LEVEL=DEBUG
    volumes:  
        - "dbsocket:/var/run/postgresql"
        - "logs:/var/log"
        - "./web:/code"
    networks:
        net1:
    ports:
        - "80:80"  # Web for all

  db:
    build: "db"
    volumes:  
        - "database:/var/lib/postgresql/data"
        - "dbsocket:/var/run/postgresql"
        - "logs:/var/log"
    networks:
        net1:
    ports:
        - "54329:5432" # DB for external SSL connections
        - "127.0.0.1:6432:6432" # DB for trusted localhost

  sync:
    build: "sync"
    command: "ash -c 'pip install -e /code && exec syncserver.py'"
    environment:
        - DEBUG=1
        - LOG_LEVEL=DEBUG
    volumes:
        - "dbsocket:/var/run/postgresql"
        - "logs:/var/log"
        - "./sync:/code"
    networks:
        net1:

networks:
  net1:

volumes:
  database:  # for long term storage of database/config
  dbsocket:  # for sharing of database unix socket across containers
  logs:      # for long term storage of logging data

