---
# This compose file is meant for development purposes
# It mounts the local user's directory and creates a link in the web container
# so that it uses the local copy of the web service
#
# We use a script to create a docker-compose file for deployment with specific
# images on docker hub and remove the extra developement features

version: '3.2'
services:

  web:
    build:   "web"
    command: "ash -c 'pip install -e /code && webserver.py'"
    environment:
        - NWRSC_DEBUG=1
    volumes:  
        - "dbsocket:/var/run/postgresql"
        - "./web:/code"
    networks:
        net1:
    ports:
        - "80:80"  # Web for all

  db:
    build: "db"
    volumes:  
        - "database:/var/lib/postgresql/data"
        - "dbsocket:/var/run/postgresql"
    networks:
        net1:
    ports:
        - "54329:5432" # DB for external SSL connections
        - "127.0.0.1:6432:6432" # DB for trusted localhost

networks:
  net1:

volumes:
  database:
  dbsocket:

