version: '3.2'
volumes:
    database:
    socket:
    logs:
    uploads:
    certs: { external: { name: "certs" }}
    webdata:
    emaildata:
    crondata:

networks: 
    net1:

services:
  db:
    image: drytoastman/scdb:latest
    networks: { net1: {}}
    ports: 
        - '54329:5432'
        - '6432:6432'
    volumes: 
        - database:/var/lib/postgresql/data
        - socket:/var/run/postgresql
        - logs:/var/log
        - certs:/certs

  web:
    image: drytoastman/scpython:latest
    command: webserver.py
    networks: { net1: {}}
    ports: 
        - '80:80'
    volumes: 
        - socket:/var/run/postgresql
        - logs:/var/log
        - uploads:/var/uploads
        - webdata:/webdata:ro
    environment: 
        - IS_MAIN_SERVER=1
        - SHOWLIVE=0
        - MAIL_SEND_FROM=mailman@scorekeeper.wwscc.org
        - MAIL_SEND_DEFAULT_REPLYTO=admin@scorekeeper.wwscc.org
        - SECRETS_FILE=/webdata/websecrets.json
        - EMAIL_BLACKLIST=mail.ru

  email:
    image: drytoastman/scpython:latest
    command: mailman
    networks: { net1: {}}
    volumes: 
        - socket:/var/run/postgresql
        - logs:/var/log
        - uploads:/var/uploads
        - emaildata:/emaildata:ro
    environment:
        - MAIL_RECEIVE_HOST=192.168.64.1
        - MAIL_SEND_HOST=192.168.64.1
        - MAIL_SEND_FROM=mailman@scorekeeper.wwscc.org
        - MAIL_SEND_DEFAULT_REPLYTO=admin@scorekeeper.wwscc.org
        - SECRETS_FILE=/emaildata/emailsecrets.json

  cron:
    image: drytoastman/scpython:latest
    command: crondaemon
    networks: { net1: {}}
    volumes: 
        - socket:/var/run/postgresql
        - logs:/var/log
        - crondata:/crondata:ro
        - webdata:/webdata:ro
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/crondata/scorekeeper.creds.json
        - SECRETS_FILE=/webdata/websecrets.json
        - MAIL_ADMIN_ADDRESS=admin@scorekeeper.wwscc.org
