DROP TRIGGER ordercon ON runorder;
CREATE CONSTRAINT TRIGGER ordercon AFTER INSERT OR UPDATE ON runorder DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE runorderconstraints('<seriesname>');

DROP TRIGGER classordercon ON classorder;
CREATE CONSTRAINT TRIGGER classordercon AFTER INSERT OR UPDATE ON classorder DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE classorderconstraints('<seriesname>');

ALTER TABLE events ADD COLUMN spclasses TEXT[] NOT NULL DEFAULT '{}';
